# frozen_string_literal: true

source "https://rubygems.org"

# Jekyll is used in CI to assemble the Sphinx HTML into the GitHub Pages
# site at https://carlonicolini.github.io/skfolio-regime/
gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"
